### ISSUE TITLE
你好，数据集样式问题

### ISSUE THREAD

**Issue by hziheng** [ZM-BAD/ACSclassifier#2]
你好，能给个数据集中一条数据的样式是什么样的吗，或者可以说明下数据集是什么样子的吗

**Comment by ZM-BAD** [comment]
我已经毕业了，拿不到数据，也记不得了。model的data.py有read_from_csv方法，你可以大致看下读取过程。实在抱歉没能帮到你

**Comment by hziheng** [comment]
没事，感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ming Zhou"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月21日(星期六) 下午3:55
收件人:&nbsp;"ZM-BAD/ACSclassifier"<ACSclassifier@noreply.github.com&gt;;
抄送:&nbsp;"huang"<1034235826@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ZM-BAD/ACSclassifier] 你好，数据集样式问题 (#2)




我已经毕业了，拿不到数据，也记不得了。model的data.py有read_from_csv方法，你可以大致看下读取过程。实在抱歉没能帮到你
